language: node_js
node_js:
- node
script:
- yarn lint
- yarn coverage
- npm run build
after_script:
- "./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT"
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/reports-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  mvn clean deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: xKlWz1ue9bL+Gz6+Qk0bdQtvLcWjE8eJf76WGbEomFQnshVS4fY+b5pmAlP5ulnV2uOdVdH8MugMxZmSIEEfBwMvbclk01zGcaQF6/G2Z2xdDJdxCe5gzSCWi2yXFezeT0N8NRw2gDHUgjlmlYyY/8lGET5Ef7QVXUXfuT/HR4WmIWfVeDNkNHhVzgm/bZ9awqYamFQlQwgqS6ZFRk0BWQBxhDYC18Lwk55axRKaO1/xN+QSNQd64BzuSSpVCoA4y47a/kNFbdSB5FSqAvapAdWXGA2coCpCAd775tQuN7ANglnnw86BYq0WMEsobrBgl+P+zWA+K4x9dEV/i2ywDKkNerGR2HZ8d2glOUgvIDsme1Isj5Y5gpsC+cXRStLBSwBV1JG59NY4sT/VRbuUdH0i4YezOVfAns5AuyODyb4AgY42kFiPnACiaBy9e6a+bG0PfrsU97bRf1qg3ATYuNqlJtWXwIr4qQXbM2uRC5HgEhoEGjpED5/JiWrW693EvJnLK+HTi4HVcg60BhLPrrX9swJCx19ITg2qSIrM7o1g9pCCc5VoL3JkVe/DU3TvcRk3MTVSufN4ApKy+BarI6lV9+2XEwsq0N5MaiFPZJ7iQ+43vv+rrL44atUP6tTwWd5I1vk27m/72P992GHQwlC+ny4UbSitgX2TZK95opU=
  - secure: xJrRzsbn39sFR6pHHYVIhQnMLu3mLGp9QHh/XNOKC79+3NjbJ9BZJatVRCPh+jd56BA7/pkFDUqf81VnwtWwYbS15EeF63+H01ja2jMFYRrt1O+Pkv4wp8oLetSasMRd8jsbCeGSrQGEJZYjExxg5stWqrPN4eW38895/ROp2XwoQyJPcVUbAuQIgQ7KpoQy5Br1Er9s4gMH6595sE4O10YH+l/C07uJMeJ5A6j+CyaECU4/gohLHZ7M+4y+rtVQPFKqdvVFDO2sRQt25R08ckEau9YIoHpMPOOzY78Dbyq8CgNH+P5fs0qgQfQOOFf1SxTxlIKSz6F9jpxU6Zd8Ovt3KdzO6/EEpXenM6WbHV8/paHAC9ZJe7eJWsUD/92IUYxsVXNbt1D5m32BxT+hXH+/Hea9jyDc+EIaMIxDRsxOT9AXHQR7SNxirjmEJPEqTwFxWM2pLqmXPEgKLkzHd7a7UiKOBlpcUb9foD4Wck4H8ezLZJZ4AdbU0jL3zLaut0z1XpDHjtYoLIbA5a+QyuIaKRHoye/rkyevh/WQNh5vZxbTzoJeDcFMaCMSKLabLOxs9FvurVUnaghDkoLKSQkLG9c4B23xCTFXdJNqWWMsKmmgoflQNIW6vf8hp8qbSk5nZr5kJYWN0tcnlnorZo11AYT9xRHvRYzCWjBPOdU=
