language: node_js
node_js:
- node
script:
- yarn lint
- yarn coverage
- npm run build
after_script:
- "./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT"
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/reports-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then mvn clean
  deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: DVJjucf0l4ZCH6YtxADwsBkrxqPPD1rWsHUcje4+4r+n0GC43GyIusEwfhYKSoqqY19iwCkIV8noQ6BB0Xp9fdO8jaYT6AqRi50+133nV0okgs1+u30obZ8xYiQqigrX4KLGwxkzjEpbNQdBfll7WNMlohR7Y44y5ByJcx+lUSs2XbH9eBfNcSWC5eOQyMeVcidRroJJJJZe43z/VH1CM3/CeJ7sAABncE77VOuYI9jgaY5ff21tcyCUokqnZUymxPVB3CbZw5egVdj1sruastW1sjjf3KscikzsSBpDRuWV+YQFH3q5+GO0lUNdQ0ophfwkriPnSjokTKcO+DhRcxtmgJQwTnfUMeDuX2/KMe7NTRgdThBdnWypXSJjGQ0sctMy2/SHCuV1geV1MnkeeF/z9kaykAfqCeokeC3G612okq67+CqWRu4f5joy2RlvIhlUb/QsNsDXc4AUYdw7odvpKlrteGKw1OZSe6h08roeTGqjOGbupBEhFYOLvCY+n7fSdMrDMCjsIFvH0c9Epf7d305O5n0Z76XQnrwmKljy+bz9OdIIFsIYkVjjlFjeNGOZtnRgWyxcvZAH45JR0difmnNAV2gHZq4to/+5nMxOkjD/luA0PL/UzJlkPqQCQCcnbi19jf+fiMR0+OzmOG8vseU/OONIOQAYbD6DO+Q=
  - secure: mBO8fYnGWpkT/aPw73YJwj53sVRr/rJ1IhBnxkM2LXNCkwwW51SyckVsZR1oeb23c7FfgAIR32nd0ugimzfFIJmJVgiucoo3k6LM7Ej6Ppi9g5tcO8WXHIBoStpkhkzq7FxeWC8DbfZuXsVRSApaqb/gZWuQQrpupW3ihzdt48XZSRWOIdcPonxcTIHOJy77HWDhUvv6NAGEHU2whBBhbZpVfj8akToXS1a+BgnMSGvsAbebGw4srSBlw9xT2M2pN7tZfMsEo1As5Hh1Bbx2G4xWr1KS2LEnmgd4JO+x6npzaXU7ZbQVhMteY69sKG+FMBXE0Ef4Eox03KiczR3XTRlk0V3dWUXJDzH0WczElBbF3+HGBZ5UDY2z4znGHUb/SocKOe4SUAQoGrGVXdGde9XRNVPGzTWNgD6azougCa+0XVDGu4DJS9uPLvZeD9FoWDIUIU8U5UDRLEL1X7fkOJ02ELWUVXJAxo2irxji2hNpUWnovYtYIfzPnvu150JfU7ttLV8soNbNA3+hhP7V4jCv7rAhpZ/EF/UM1O88mr8lvchhQ9/SkJA9jaKdBfUSTZJ06ouZQFZH5QZFeqTvky1QGmiB70d7gtrFxHekAJko0bn7by87HbQK4zBDdiXEOuyVDLJtoz+ZIOjoFevd1SSm2NTC27jPAco9OG5XxF8=
